apiVersion: v1
kind: Pod
metadata:
  name: sample-hostaliases
spec:
  hostNetwork: true
  containers:
    - name: nginx-container-1
      image: nginx:1.17
  hostAliases:
    - ip: 8.8.8.8
      hostnames:
        - google-dns
        - google-public-dns
