---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-clusterip-vip-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: amsy810/echo-nginx:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip-vip
spec:
  type: ClusterIP
  clusterIP: 10.96.0.100
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
