---
apiVersion: v1
kind: Service
metadata:
  name: sample-none-selector-svc # term 1
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  # selectorがない
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sample-none-selector-svc # term 1
subsets:
  - addresses:
      - ip: 192.168.1.1
      - ip: 192.168.1.2
    ports:
      - protocol: TCP
        port: 80
---
# TODO EndpointsSliceについて調べる
# k describe service sample-none-selector-svc
